from machine import Pin
from utime import sleep
led1=Pin(16,Pin.OUT)
led2=Pin(17,Pin.OUT)
led3=Pin(18,Pin.OUT)
led4=Pin(19,Pin.OUT)
led5=Pin(20,Pin.OUT)
led6=Pin(21,Pin.OUT)




def giant_led():
    led1.value(1)
    sleep(0.3)
    led1.value(0)
    led2.value(1)
    sleep(0.3)
    led2.value(0)
    led3.value(1)
    sleep(0.3)
    led3.value(0)
    led4.value(1)
    sleep(0.3)
    led4.value(0)
    led5.value(1)
    sleep(0.3)
    led5.value(0)
    led6.value(1)
    sleep(0.3)
    led1.value(1)
    sleep(0.3)
    led1.value(0)
    led2.value(1)

    sleep(0.3)
    led2.value(0)
    led3.value(1)
    sleep(0.3)
    led3.value(0)
    led4.value(1)
    sleep(0.3)
    led4.value(0)
    led5.value(1)
    sleep(0.3)
    led1.value(1)
    sleep(0.3)
    led1.value(0)
    led2.value(1)
    sleep(0.3)
    led2.value(0)
    led3.value(1)
    sleep(0.3)
    led3.value(0)
    led4.value(1)
    sleep(0.3)
    led1.value(1)
    sleep(0.3)
    led1.value(0)
    led2.value(1)
    sleep(0.3)
    led2.value(0)
    led3.value(1)
    sleep(0.3)
    led1.value(1)
    sleep(0.3)

    led1.value(0)
    led2.value(1)
    sleep(0.3)
    led1.value(1)
    sleep(0.5)

    led6.value(0)
    sleep(0.3)
    led5.value(0)
    sleep(0.3)
    led4.value(0)
    sleep(0.3)
    led3.value(0)
    sleep(0.3)
    led2.value(0)
    sleep(0.3)
    led1.value(0)
    sleep(0.3)
    
    led1.value(1)
    sleep(0.3)
    led2.value(1)
    sleep(0.3)
    led3.value(1)
    sleep(0.3)
    led4.value(1)
    sleep(0.3)
    led5.value(1)
    sleep(0.3)
    led6.value(1)
    sleep(0.3)
    
    led6.value(0)
    led5.value(0)
    led4.value(0)
    led3.value(0)
    led2.value(0)
    led1.value(0)
    sleep(.3)
    
    led1.toggle()
    sleep(.3)
    led2.toggle()
    sleep(.3)
    led3.toggle()
    sleep(.3)
    led4.toggle()
    sleep(.3)
    led5.toggle()
    sleep(.3)
    led6.toggle()
    sleep(.3)
    
    led1.toggle()
    sleep(.3)
    led2.toggle()
    sleep(.3)
    led3.toggle()
    sleep(.3)
    led4.toggle()
    sleep(.3)
    led5.toggle()
    sleep(.3)
    led6.toggle()
    sleep(.3)

    led6.value(1)
    led5.value(0)
    led4.value(1)
    led3.value(0)
    led2.value(1)
    led1.value(0)
    sleep(.6)
    
    led6.value(0)
    led5.value(1)
    led4.value(0)
    led3.value(1)
    led2.value(0)
    led1.value(1)
    sleep(.6)
    
    led6.value(1)
    led5.value(0)
    led4.value(1)
    led3.value(0)
    led2.value(1)
    led1.value(0)
    sleep(.6)
    
    
    
    led6.value(0)
    led5.value(1)
    led4.value(0)
    led3.value(1)
    led2.value(0)
    led1.value(1)
    sleep(.6)
    
    led6.value(1)
    led5.value(0)
    led4.value(1)
    led3.value(0)
    led2.value(1)
    led1.value(0)
    sleep(.6)
    
    led6.value(0)
    led5.value(1)
    led4.value(0)
    led3.value(1)
    led2.value(0)
    led1.value(1)
    sleep(.6)
    
    led6.value(1)
    led5.value(0)
    led4.value(1)
    led3.value(0)
    led2.value(1)
    led1.value(0)
    sleep(.6)
    
    
    
    led6.value(0)
    led5.value(1)
    led4.value(0)
    led3.value(1)
    led2.value(0)
    led1.value(1)
    sleep(.6)
    
    led6.value(0)
    led5.value(0)
    led4.value(0)
    led3.value(0)
    led2.value(0)
    led1.value(0)
    sleep(.3)
    
    led6.value(0)
    led5.value(0)
    led4.value(0)
    led3.value(1)
    led2.value(1)
    led1.value(1)
    sleep(.6)
    
    led6.value(1)
    led5.value(1)
    led4.value(1)
    led3.value(0)
    led2.value(0)
    led1.value(0)
    sleep(.6)
    
    led6.value(0)
    led5.value(0)
    led4.value(0)
    led3.value(1)
    led2.value(1)
    led1.value(1)
    sleep(.6)
    
    led6.value(1)
    led5.value(1)
    led4.value(1)
    led3.value(0)
    led2.value(0)
    led1.value(0)
    sleep(.6)
    
    led6.value(0)
    led5.value(0)
    led4.value(0)
    led3.value(1)
    led2.value(1)
    led1.value(1)
    sleep(.6)
    
    led6.value(1)
    led5.value(1)
    led4.value(1)
    led3.value(0)
    led2.value(0)
    led1.value(0)
    sleep(.6)
    
    led6.value(0)
    led5.value(0)
    led4.value(0)
    led3.value(0)
    led2.value(0)
    led1.value(0)
    sleep(.6)
    
    led6.value(1)
    led5.value(1)
    led4.value(1)
    led3.value(1)
    led2.value(1)
    led1.value(1)
    sleep(.5)
    
    led6.value(0)
    led5.value(0)
    led4.value(0)
    led3.value(0)
    led2.value(0)
    led1.value(0)
    sleep(.6)
    
    led6.value(1)
    led5.value(1)
    led4.value(1)
    led3.value(1)
    led2.value(1)
    led1.value(1)
    sleep(.6)
    
    
    
def all_on():
    led1.value(1)
    sleep(0.3)
    led2.value(1)
    sleep(0.3)
    led3.value(1)
    sleep(0.3)
    led4.value(1)
    sleep(0.3)
    led5.value(1)
    sleep(0.3)
    led6.value(1)
    sleep(0.3)
    
def fill_up():
    led1.value(1)
    sleep(0.3)
    led1.value(0)
    led2.value(1)
    sleep(0.3)
    led2.value(0)
    led3.value(1)
    sleep(0.3)
    led3.value(0)
    led4.value(1)
    sleep(0.3)
    led4.value(0)
    led5.value(1)
    sleep(0.3)
    led5.value(0)
    led6.value(1)
    sleep(0.3)
    led1.value(1)
    sleep(0.3)
    led1.value(0)
    led2.value(1)

    sleep(0.3)
    led2.value(0)
    led3.value(1)
    sleep(0.3)
    led3.value(0)
    led4.value(1)
    sleep(0.3)
    led4.value(0)
    led5.value(1)
    sleep(0.3)
    led1.value(1)
    sleep(0.3)
    led1.value(0)
    led2.value(1)
    sleep(0.3)
    led2.value(0)
    led3.value(1)
    sleep(0.3)
    led3.value(0)
    led4.value(1)
    sleep(0.3)
    led1.value(1)
    sleep(0.3)
    led1.value(0)
    led2.value(1)
    sleep(0.3)
    led2.value(0)
    led3.value(1)
    sleep(0.3)
    led1.value(1)
    sleep(0.3)

    led1.value(0)
    led2.value(1)
    sleep(0.3)
    led1.value(1)
    sleep(0.5)
    
def led_one():
    led1.value(1)
    sleep(.5)
    led1.value(0)
    
def led_two():
    led2.value(1)
    sleep(.5)
    led2.value(0)
    
def toggle():
    led1.toggle()
    led2.toggle()
    led3.toggle()
    led4.toggle()
    led5.toggle()
    led6.toggle()